name: CI Workflow

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
      - develop
      - feature/*
      - bugfix/*
  pull_request:
      branches: [dev, master]
